sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t bhumika/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bhumika/docker-react npm run test
